// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmGzh7VO1xccevR_GLe58XXcf_MT-ulX4',
    appId: '1:181787299060:web:7958e016a3da7581b1e2a1',
    messagingSenderId: '181787299060',
    projectId: 'flutter-final-assignment',
    authDomain: 'flutter-final-assignment.firebaseapp.com',
    storageBucket: 'flutter-final-assignment.firebasestorage.app',
    measurementId: 'G-G8C43NJED0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI55kZl9IiChjJo86YyXvkYg7KONDJ1sY',
    appId: '1:181787299060:android:e628a17673e1736bb1e2a1',
    messagingSenderId: '181787299060',
    projectId: 'flutter-final-assignment',
    storageBucket: 'flutter-final-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi8kI9j-EVkG1RqHu12H93s7KYUbMM7bA',
    appId: '1:181787299060:ios:eea4b3820628aa61b1e2a1',
    messagingSenderId: '181787299060',
    projectId: 'flutter-final-assignment',
    storageBucket: 'flutter-final-assignment.firebasestorage.app',
    androidClientId: '181787299060-q5o3vvgehf70b765fb7ff30n6ad7u5nb.apps.googleusercontent.com',
    iosClientId: '181787299060-oibkg4mvhsl8asn1uenn3chtdoo3ul8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi8kI9j-EVkG1RqHu12H93s7KYUbMM7bA',
    appId: '1:181787299060:ios:eea4b3820628aa61b1e2a1',
    messagingSenderId: '181787299060',
    projectId: 'flutter-final-assignment',
    storageBucket: 'flutter-final-assignment.firebasestorage.app',
    androidClientId: '181787299060-q5o3vvgehf70b765fb7ff30n6ad7u5nb.apps.googleusercontent.com',
    iosClientId: '181787299060-oibkg4mvhsl8asn1uenn3chtdoo3ul8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmGzh7VO1xccevR_GLe58XXcf_MT-ulX4',
    appId: '1:181787299060:web:5b0ea070868b6ff0b1e2a1',
    messagingSenderId: '181787299060',
    projectId: 'flutter-final-assignment',
    authDomain: 'flutter-final-assignment.firebaseapp.com',
    storageBucket: 'flutter-final-assignment.firebasestorage.app',
    measurementId: 'G-2BQ4VC74EG',
  );
}
